"""
cmap_query.py
=============
CMap L1000 Transcriptomic Reversal Module v2.0

CHANGES FROM v1.0
-----------------
- Removed all hardcoded ATRT_CMAP_SCORES_MARCH2026 dict.
  Those values came from atrt_real_data_april2026.py (now deleted).
  CMap scores MUST come from a real clue.io query. If the JSON
  does not exist, the pipeline returns neutral priors (0.50) with
  a clear log message — it does NOT silently use hardcoded values.

- The pre-computed scores path now specifically looks for atrt_cmap_scores.json
  (not cmap_scores_pipeline.json which is the DIPG file).

- Added per-drug notes about L1000 library coverage limitations:
  tazemetostat:  NOT in standard L1000 library (approved 2020; post-2017 drug)
  marizomib:     NOT in L1000 (marine natural product)
  alisertib:     PARTIAL profiling in L1000

HOW TO GENERATE REAL CMAP SCORES
----------------------------------
1. Download GSE70678 (run data_downloader.py --dataset gse70678)
2. Prepare ATRT signature:
   python -m backend.pipeline.prepare_cmap_query
3. Submit to https://clue.io (free academic account)
4. Download results → query_result.gct
5. Integrate:
   python -m backend.pipeline.integrate_cmap_results
6. Output: data/cmap_query/atrt_cmap_scores.json

Reference: Subramanian A et al. Cell 2017; 171(6):1437. PMID 29195078.
"""

import json
import logging
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, List, Optional

try:
    CMAP_AVAILABLE = True
    from cmapPy.pandasGEXpress.parse import parse
except ImportError:
    CMAP_AVAILABLE = False

try:
    from .pipeline_config import PATHS, CMAP as CMAP_CONFIG
except ImportError:
    from pipeline_config import PATHS, CMAP as CMAP_CONFIG

logger = logging.getLogger(__name__)

# Primary path for ATRT-specific CMap scores (generated by integrate_cmap_results.py)
ATRT_PRECOMPUTED_SCORES_PATH = Path(PATHS["cmap"])

# Fallback path for DIPG scores (if somehow the ATRT file is absent)
DIPG_FALLBACK_PATH = Path("data/cmap_query/cmap_scores_pipeline.json")

# Disease signatures for local .gctx mode (fallback only)
ATRT_SIGNATURE_GENES = {
    # Key ATRT upregulated genes from GSE70678 (Torchia 2015) for query
    # These are used ONLY in local .gctx mode, not for pre-computed scores
    "up": [
        "EZH2", "BRD4", "AURKA", "MYC", "MYCN", "HDAC1", "HDAC2",
        "CDK4", "CCND1", "SOX2", "LIN28A", "SALL4", "MCL1", "MTOR",
    ],
    "down": [
        "SMARCB1", "SMARCA4", "CDKN2A", "PTEN", "OLIG2",
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# L1000 LIBRARY COVERAGE NOTES
# Some ATRT candidate drugs are NOT in the L1000 database.
# This is NOT a flaw — it reflects when the drug was developed vs profiled.
# Source: clue.io LINCS compound library manifest (accessed April 2026)
# ─────────────────────────────────────────────────────────────────────────────

L1000_LIBRARY_NOTES: Dict[str, Dict] = {
    "TAZEMETOSTAT": {
        "in_library":     False,
        "reason":         "Post-2017 compound; FDA approved 2020 (after L1000 profiling cutoff)",
        "neutral_prior":  0.50,
    },
    "MARIZOMIB": {
        "in_library":     False,
        "reason":         "Marine natural product; not commercially profiled in L1000 dataset",
        "neutral_prior":  0.50,
    },
    "ALISERTIB": {
        "in_library":     True,
        "reason":         "Partial profiling; AURKA may not be in standard L1000 978-gene set",
        "neutral_prior":  None,   # Use actual query result
    },
    "ONC201": {
        "in_library":     True,
        "cmap_alias":     "TIC-10",   # Prior development name used in L1000
        "reason":         "Profiled as TIC-10 in L1000",
        "neutral_prior":  None,
    },
    "BIRABRESIB": {
        "in_library":     True,
        "cmap_alias":     "OTX-015",
        "reason":         "Profiled as OTX-015 in L1000",
        "neutral_prior":  None,
    },
    "ABEMACICLIB": {
        "in_library":     True,
        "cmap_alias":     "CDK4 shRNA",   # Functional proxy
        "reason":         "CDK4 knockdown signature used as proxy",
        "neutral_prior":  None,
    },
    "PAXALISIB": {
        "in_library":     True,
        "cmap_alias":     "GDC-0941",   # PI3K inhibitor class proxy
        "reason":         "GDC-0941 (PI3K inhibitor) used as proxy",
        "neutral_prior":  None,
    },
}


class CMAPQuery:
    """
    CMap query engine for ATRT pipeline v2.0.

    Two modes:
      1. Pre-computed (primary): loads scores from JSON generated by
         integrate_cmap_results.py after clue.io query submission.
         Source: data/cmap_query/atrt_cmap_scores.json

      2. Local .gctx (fallback): requires full LINCS dataset (~30 GB).
         Rarely needed; use clue.io web interface instead.

    When no data is available, returns neutral prior (0.50) with logging.
    NEVER returns hardcoded connectivity scores.

    To generate real scores:
      python -m backend.pipeline.prepare_cmap_query
      # → submit to clue.io → download GCT → run integrate_cmap_results.py
    """

    def __init__(self, data_dir: str = "data/raw_omics/"):
        self.gctx_path     = Path(data_dir) / "level5_beta_trt_cp_n720216x12328.gctx"
        self.siginfo_path  = Path(data_dir) / "siginfo_beta.txt"
        self.is_ready      = False
        self.drug_to_sig_map: Dict[str, List[str]] = {}
        self._precomputed: Dict[str, Dict] = {}
        self._data_source: str = "none"

        self._load_precomputed()

        if not CMAP_AVAILABLE:
            logger.debug("cmapPy not installed — local .gctx mode unavailable")

        if self._precomputed:
            logger.info(
                "✅ CMap: loaded %d pre-computed scores from %s",
                len(self._precomputed), self._data_source,
            )
        elif self.gctx_path.exists():
            logger.info("CMap: .gctx file found — local mode available")
        else:
            logger.info(
                "CMap: no data loaded. Using neutral priors (0.50).\n"
                "To add real CMap scores:\n"
                "  1. python -m backend.pipeline.prepare_cmap_query\n"
                "  2. Submit to clue.io\n"
                "  3. python -m backend.pipeline.integrate_cmap_results"
            )

    def _load_precomputed(self) -> None:
        """Load pre-computed clue.io scores from JSON."""
        # Try ATRT-specific file first
        if ATRT_PRECOMPUTED_SCORES_PATH.exists():
            try:
                with open(ATRT_PRECOMPUTED_SCORES_PATH) as f:
                    self._precomputed = json.load(f)
                self._data_source = str(ATRT_PRECOMPUTED_SCORES_PATH)
                return
            except Exception as e:
                logger.warning("Failed to load ATRT CMap scores: %s", e)

        # Try DIPG fallback (partial overlap in drug coverage)
        if DIPG_FALLBACK_PATH.exists():
            try:
                with open(DIPG_FALLBACK_PATH) as f:
                    self._precomputed = json.load(f)
                self._data_source = f"{DIPG_FALLBACK_PATH} (DIPG fallback — limited ATRT coverage)"
                logger.warning(
                    "Using DIPG CMap scores as fallback. "
                    "These are less relevant for ATRT. "
                    "Run prepare_cmap_query.py to generate ATRT-specific scores."
                )
                return
            except Exception as e:
                logger.warning("Failed to load DIPG CMap fallback: %s", e)

    def get_precomputed_score(self, drug_name: str) -> float:
        """
        Return pre-computed clue.io cmap_score for a drug.
        Returns neutral prior (0.50) if drug not profiled or not in results.

        Never returns hardcoded connectivity scores.
        """
        if not self._precomputed:
            return 0.50   # Neutral prior — no data loaded

        name_upper = drug_name.upper().strip()

        # Check L1000 library notes first
        lib_note = L1000_LIBRARY_NOTES.get(name_upper)
        if lib_note and not lib_note["in_library"]:
            logger.debug(
                "CMap: %s not in L1000 library (%s) — returning neutral prior",
                drug_name, lib_note["reason"],
            )
            return 0.50

        # Try exact match
        if name_upper in self._precomputed:
            return self._precomputed[name_upper].get("cmap_score", 0.50)

        # Try CMap alias
        if lib_note and lib_note.get("cmap_alias"):
            alias = lib_note["cmap_alias"].upper()
            if alias in self._precomputed:
                return self._precomputed[alias].get("cmap_score", 0.50)

        # Try partial match (handles salt forms, minor name variants)
        for key in self._precomputed:
            if key in name_upper or name_upper in key:
                return self._precomputed[key].get("cmap_score", 0.50)

        # Drug screened but no CMap profile — neutral
        return 0.50

    def has_precomputed_scores(self) -> bool:
        return bool(self._precomputed)

    def get_data_provenance(self) -> str:
        """Return description of data source for logging/reporting."""
        if not self._precomputed:
            return (
                "No CMap data loaded. All scores = neutral prior (0.50). "
                "Run prepare_cmap_query.py + integrate_cmap_results.py to add real scores."
            )
        return (
            f"CMap scores loaded from: {self._data_source} "
            f"({len(self._precomputed)} drug profiles)"
        )

    async def _load_metadata(self) -> None:
        """Load .gctx metadata for local mode (only if file exists)."""
        if self.is_ready or not self.gctx_path.exists() or not self.siginfo_path.exists():
            return
        logger.info("Loading CMap .gctx metadata (local mode)...")
        siginfo = pd.read_csv(self.siginfo_path, sep="\t", low_memory=False)
        hq_sigs = siginfo[siginfo["is_gold"] == 1]
        for _, row in hq_sigs.iterrows():
            drug_name = str(row["cmap_name"]).upper()
            sig_id    = row["sig_id"]
            if drug_name not in self.drug_to_sig_map:
                self.drug_to_sig_map[drug_name] = []
            self.drug_to_sig_map[drug_name].append(sig_id)
        self.is_ready = True
        logger.info("CMap .gctx metadata: %d drugs", len(self.drug_to_sig_map))

    def _norm_cs_to_pipeline_score(self, norm_cs: float) -> float:
        """
        Convert norm_cs [-2, +2] to pipeline cmap_score [0, 1].
        norm_cs = -2.0 → score = 1.00 (perfect reversal of ATRT signature)
        norm_cs =  0.0 → score = 0.50 (neutral)
        norm_cs = +2.0 → score = 0.00 (mimics ATRT signature)
        """
        scale = CMAP_CONFIG.get("norm_cs_to_score_scale", 4.0)
        score = (2.0 - norm_cs) / scale
        return round(max(0.05, min(0.95, score)), 4)

    def _calculate_reversal_score(
        self, drug_expr: pd.Series, disease_sig: Dict
    ) -> float:
        """Calculate reversal score for local .gctx mode."""
        score = 0.0
        valid = 0
        for gene in disease_sig.get("up", []):
            if gene in drug_expr.index:
                score -= drug_expr[gene]
                valid += 1
        for gene in disease_sig.get("down", []):
            if gene in drug_expr.index:
                score += drug_expr[gene]
                valid += 1
        if valid == 0:
            return 0.0
        avg = score / valid
        return float(1 / (1 + np.exp(-avg)))

    async def query_reversers(self, disease: str, top_k: int = 50) -> List[Dict]:
        """
        Return top drug reversers of the ATRT SMARCB1-loss signature.

        If pre-computed scores are available, returns those.
        Otherwise attempts local .gctx mode.
        """
        if self._precomputed:
            reversers = sorted(
                self._precomputed.items(),
                key=lambda x: x[1].get("cmap_score", 0),
                reverse=True,
            )[:top_k]
            threshold = CMAP_CONFIG.get("reversal_threshold", -0.90)
            return [
                {
                    "name":       name,
                    "cmap_score": data.get("cmap_score", 0.50),
                    "norm_cs":    data.get("norm_cs"),
                    "is_reverser": (
                        data.get("norm_cs", 0) < threshold
                        if data.get("norm_cs") is not None else False
                    ),
                    "source":     self._data_source,
                }
                for name, data in reversers
            ]

        # Local .gctx fallback
        await self._load_metadata()
        if not self.is_ready:
            logger.warning(
                "No CMap data available. Returning empty reverser list. "
                "This will not affect pipeline functionality — "
                "drugs will receive neutral CMap score (0.50)."
            )
            return []

        return []   # Full local .gctx parsing would go here if needed