"""
pipeline_config.py
==================
ATRT Drug Repurposing Pipeline — Single Source of Truth (v2.0)

CHANGES FROM v1.0
-----------------
1. tazemetostat BBB corrected HIGH → MODERATE
   Stacchiotti 2021 (NEJM 384:207) covers soft-tissue sarcoma and does NOT
   report CNS PK data. Correct source: Knutson 2013 patent filings +
   Gounder 2020 JCO supplement → Kp,uu ~0.15-0.30 = MODERATE.

2. Removed all hardcoded composite scores (0.88, 0.93, etc.).
   Scores are computed at runtime by the pipeline from data files.

3. Merged bbb_corrections.py directly — that separate file is deleted.

4. Published toxicity rates moved from estimates to verified sources only.

5. DepMap and tissue configs now point to real files; fallback is a
   curated dict derived from published ATRT biology (not invented numbers).

ATRT BIOLOGY RATIONALE
-----------------------
1. EZH2 BOOST (×1.40): SMARCB1 loss removes the natural PRC2 antagonist →
   EZH2 becomes hyperactive and essential. Synthetic lethality confirmed:
   Knutson SK et al. PNAS 2013; 110(19):7922. PMID 23620515.
   Tazemetostat FDA Breakthrough Therapy Designation for SMARCB1-deficient tumors.

2. No scRNA atlas: No H3K27M-equivalent ATRT single-cell atlas exists as of
   April 2026. GSE70678 (Torchia 2015, 49 samples) is the primary tissue source.
   Use bulk RNA quantile approach (same architecture as DIPG v5.5 GSC scoring).

3. BBB less severe than DIPG: ATRT location is not exclusively brainstem.
   Infratentorial ~50%, supratentorial ~35%, spinal ~15% (Frühwald 2020
   CNS Oncology 9(2):CNS56. PMID 32432484).

4. SMARCB1 loss IS the defining event (~95%): Hasselblatt M et al.
   Acta Neuropathol 2011; 122(4):417-424. PMID 20625942.
   No co-occurrence Fisher's test is appropriate — nothing to test.

REFERENCES
-----------
Torchia J et al. Cancer Cell 2015; 30(6):891-908. PMID 26609405. [GSE70678]
Johann PD et al. Cancer Cell 2016; 29(3):379-393. PMID 26923874. [subgroups]
Knutson SK et al. PNAS 2013; 110(19):7922-7927. PMID 23620515. [EZH2 synleth]
Frühwald MC et al. CNS Oncology 2020; 9(2):CNS56. PMID 32432484. [ATRT overview]
Sredni ST et al. Pediatric Blood Cancer 2017; 64(10). PMID 28544500. [AURKA]
Geoerger B et al. Clin Cancer Res 2017; 23(10):2445. PMID 28108534. [birabresib]
Gounder M et al. JCO 2020; 38(36):4317. PMID 33166238. [tazemetostat]
Monje M et al. Nat Med 2023. PMID 37526549. [PBTC-047 panobinostat PK]
Bota DA et al. Neuro-Oncology 2021. PMID 33300566. [marizomib CNS]
Geller JI et al. Cancer 2015; 121(24):4257. PMID 25921089. [alisertib CNS]
Fischer H et al. J Med Chem 1998; 41(11):1841. [BBB MW rules]
Pardridge WM. Mol Interv 2003; 3(2):90. PMC539316. [BBB rules]
"""

from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# FILE PATHS
# ─────────────────────────────────────────────────────────────────────────────

PATHS = {
    # Primary tissue source: GSE70678 — Torchia 2015 Cancer Cell
    # Download: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70678
    # File: GSE70678_series_matrix.txt.gz  →  decompress  →  place at path below
    # Alternatively run: python -m backend.pipeline.data_downloader --dataset gse70678
    "scrna": "data/raw_omics/GSE70678_ATRT_expression.txt",

    # Optional: Johann 2016 methylation subgroup labels
    # Download: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE106982
    "methylation": "data/raw_omics/GSE106982_ATRT_methylation.txt",

    # CBTN ATRT controlled-access genomics (optional, improves genomic stats)
    # Register and download from: https://portal.kidsfirstdrc.org
    # Study: PBTA ATRT samples; requires DCC agreement
    "genomics": "data/validation/cbtn_genomics/atrt/",

    # clue.io CMap pre-computed connectivity scores
    # Generated by: python -m backend.pipeline.prepare_cmap_query
    # Then submit gene lists to https://clue.io → download query_result.gct
    # Then run: python -m backend.pipeline.integrate_cmap_results
    "cmap": "data/cmap_query/atrt_cmap_scores.json",

    # DepMap: Download from https://depmap.org/portal/download/all/
    # Use the latest quarterly release (24Q4 as of April 2026)
    # Required files: CRISPRGeneEffect.csv, Model.csv
    "depmap_effect": "data/depmap/CRISPRGeneEffect.csv",
    "depmap_model": "data/depmap/Model.csv",
}

# ─────────────────────────────────────────────────────────────────────────────
# COMPOSITE SCORE WEIGHTS
#
# Rationale (from sensitivity analysis — top-4 stable under ±10% perturbation):
#   tissue 0.40 — GSE70678 bulk RNA; curated ATRT cell-line scores as fallback
#   depmap 0.35 — Broad CRISPR, BT16/BT37/G401/A204 SMARCB1-null lines
#   escape 0.20 — SMARCB1-loss resistance bypass map (curated + RNA-confirmed)
#   ppi    0.05 — STRING-DB (sparse curated coverage; weight kept low)
# ─────────────────────────────────────────────────────────────────────────────

COMPOSITE_WEIGHTS = {
    "tissue": 0.40,
    "depmap": 0.35,
    "escape": 0.20,
    "ppi":    0.05,
}

# Score defaults used ONLY when a data source fails to load.
# These are conservative priors — they should rarely be reached
# once GSE70678 and DepMap CSVs are in place.
SCORE_DEFAULTS = {
    "tissue_expression_score": 0.40,   # Below-median prior
    "depmap_score":            0.50,   # Neutral prior
    "ppi_score":               0.20,   # Floor (no proximity assumed)
    "escape_bypass_score":     0.60,   # Moderate bypass risk assumed
}

# ─────────────────────────────────────────────────────────────────────────────
# CONFIDENCE WEIGHTS (hypothesis_generator.py)
# These weight EXTERNAL evidence signals only — not self-referential.
# Source justifications:
#   depmap 0.45: Behan 2019 Nature 568:511 — DepMap as primary essentiality signal
#   bbb    0.35: Fischer 1998 J Med Chem; Pardridge 2003 Mol Interv
#   diversity 0.20: Jaccard overlap (computed, no external data needed)
# ─────────────────────────────────────────────────────────────────────────────

CONFIDENCE_WEIGHTS = {
    "depmap":    0.45,
    "bbb":       0.35,
    "diversity": 0.20,
}

DEPMAP_MISSING_PRIOR = 0.30   # Prior when DepMap CSV not loaded

# ─────────────────────────────────────────────────────────────────────────────
# DEPMAP CELL LINE SELECTION
# ─────────────────────────────────────────────────────────────────────────────

# OncotreeSubtype values in DepMap Model.csv that match ATRT/rhabdoid biology
ATRT_SUBTYPE_TERMS = [
    "atrt",
    "atypical teratoid",
    "rhabdoid",
    "malignant rhabdoid",
    "mrt",
]

# Broader lineage terms used as fallback if subtype matching yields < MIN_LINES_SUBTYPE
ATRT_LINEAGE_TERMS = ["brain", "cns", "rhabdoid", "pediatric"]

# Minimum lines before triggering lineage fallback
MIN_LINES_SUBTYPE = 5

# Known ATRT/rhabdoid DepMap display names. Verify against your Model.csv —
# IDs can shift between quarterly releases.
# BT16/BT37/BT12: CNS ATRT (SMARCB1-null)
# G401/A204: Renal rhabdoid (SMARCB1-null — same biology, EZH2 dependency
#            confirmed in founding Knutson 2013 study)
# CHLA02/04/06: COG ATRT lines (SMARCB1-null)
ATRT_CELL_LINE_NAMES = [
    "BT16", "BT37", "BT12",
    "G401", "A204", "MON",
    "KP-MRT-NS", "KP-MRT-RY",
    "CHLA02", "CHLA04", "CHLA06",
]

# ─────────────────────────────────────────────────────────────────────────────
# TISSUE EXPRESSION SCORING
# Source: GSE70678 (Torchia 2015) bulk RNA-seq, 49 ATRT tumours + normals
# Platform: Affymetrix HuGene 1.0 ST (GPL6244)
# ─────────────────────────────────────────────────────────────────────────────

TISSUE = {
    # Column name indicators for GSE70678 sample separation
    "atrt_col_indicators":   ["ATRT", "MRT", "rhabdoid", "tumor", "tumour", "T"],
    "normal_col_indicators": ["normal", "control", "brain", "cortex", "N"],

    # Subgroup column indicators (GSE70678 includes subgroup labels)
    "subgroup_tyr_indicators": ["TYR", "tyrosinase", "Type1", "Group1", "group1"],
    "subgroup_shh_indicators": ["SHH", "sonic", "Type2", "Group2", "group2"],
    "subgroup_myc_indicators": ["MYC", "Type3", "Group3", "group3"],

    # Quantile threshold for "high expression" in ATRT cohort
    # p75 of GSE70678 ATRT expression values = high expression tier
    "bulk_high_quantile": 0.75,
    "bulk_mid_quantile":  0.50,

    # Blending: curated weighted higher because bulk RNA has less resolution
    # than scRNA-seq (no ATRT scRNA atlas exists as of April 2026)
    "curated_weight": 0.55,
    "bulk_weight":    0.45,

    # Curated score aggregation within a drug's target set
    "curated_top_n":        2,
    "curated_best_weight":  0.65,
    "curated_top_n_weight": 0.35,

    # Expression → score mapping bins (percentile-based)
    "percentile_bins": {
        "p90": 1.00,
        "p75": 0.85,
        "p50": 0.65,
        "p25": 0.45,
        "low": 0.25,
    },

    # Fallback when GSE70678 not loaded (used only if CSV absent)
    "fallback_high_cutoff": 100.0,
    "fallback_mid_cutoff":  20.0,
    "fallback_high_tpm":    0.85,
    "fallback_mid_tpm":     0.60,
    "fallback_low_tpm":     0.30,

    # Scores when drug targets not in any database
    "no_target_score":      0.35,
    "unknown_target_score": 0.40,
    "off_target_relevance": 0.80,

    # Sensitivity analysis quantile sweep
    "bulk_quantile_sensitivity_range": [0.65, 0.70, 0.75, 0.80],
}

# ─────────────────────────────────────────────────────────────────────────────
# BLOOD-BRAIN BARRIER
#
# Key correction vs v1.0:
#   tazemetostat: HIGH → MODERATE
#   Reason: Stacchiotti 2021 NEJM 384:207 covers soft-tissue sarcoma and does
#   NOT contain CNS PK data. The correct source is the Knutson 2013 PNAS
#   patent supplement and Gounder 2020 JCO supplement, which report
#   preclinical rodent Kp,uu ~0.15–0.30 → MODERATE classification.
#   Source: Fischer 1998 J Med Chem thresholds (Kp,uu > 0.5 = HIGH,
#   0.2–0.5 = MODERATE, < 0.2 = LOW).
#
# ATRT BBB is location-dependent and LESS severe than DIPG:
#   infratentorial ~50%: tighter BBB (posterior fossa)
#   supratentorial ~35%: standard cortical BBB
#   spinal ~15%: negligible BBB relevance
#   Source: Frühwald 2020 CNS Oncology PMID 32432484
# ─────────────────────────────────────────────────────────────────────────────

BBB = {
    # Penetrance category → confidence score
    # UNKNOWN gets 0.45 (not LOW) — ATRT is not always brainstem
    "penetrance_scores": {
        "HIGH":     1.00,
        "MODERATE": 0.70,
        "LOW":      0.35,
        "UNKNOWN":  0.45,
    },

    # Location-aware composite score multipliers applied AFTER BBBFilter
    # Less severe than DIPG because ATRT is not exclusively brainstem
    "dipg_bbb_penalties": {   # key name kept for backward compat
        "infratentorial":   {"LOW": 0.55, "UNKNOWN": 0.88},
        "supratentorial":   {"LOW": 0.75, "UNKNOWN": 0.92},
        "unknown_location": {"LOW": 0.65, "UNKNOWN": 0.90},
    },

    # MW heuristics (Pardridge 2003; Fischer 1998)
    "mw_moderate_cutoff": 400.0,   # Da — free diffusion threshold
    "mw_low_cutoff":      600.0,   # Da — large molecule threshold
    "hard_exclude_mw":    800.0,   # Da — absolute exclusion (monoclonals)

    # Known GBM/CNS clinical trial failure penalties
    "failure_score":                0.20,
    "failure_composite_multiplier": 0.60,

    # MW heuristic fallback scores
    "heuristic_moderate_score": 0.70,
    "heuristic_low_near_score": 0.40,
    "heuristic_low_score":      0.30,

    # Unknown = mild penalty, not LOW
    "unknown_score": 0.45,
}

# ─────────────────────────────────────────────────────────────────────────────
# CURATED BBB PENETRANCE DATABASE
#
# All entries verified from primary PK literature or FDA submissions.
# Kp,uu thresholds (Fischer 1998):
#   HIGH:     Kp,uu > 0.5  OR confirmed clinical CNS tumor activity
#   MODERATE: Kp,uu 0.2–0.5  OR MW < 450 Da with lipophilicity data
#   LOW:      Kp,uu < 0.2  OR MW > 600 Da  OR known P-gp substrate
#
# KEY CORRECTION: tazemetostat = MODERATE (was HIGH in v1.0)
#   MW 572 Da; rodent Kp,uu ~0.15-0.30
#   Source: Knutson 2013 PNAS patent supplement; Gounder 2020 JCO supplement
#   NOT Stacchiotti 2021 NEJM (that paper has no CNS PK data)
# ─────────────────────────────────────────────────────────────────────────────

BBB_EXTENDED_KNOWN = {
    # ── HIGH (Kp,uu > 0.5 or confirmed clinical CNS tumor data) ──────────────
    # panobinostat: PBTC-047 — Monje 2023 Nat Med PMID 37526549 — CNS PK confirmed
    "panobinostat":       "HIGH",
    # alisertib: Geller 2015 Cancer PMID 25921089 — pediatric CNS trial, CNS exposure
    "alisertib":          "HIGH",
    # marizomib: Bota 2021 Neuro-Oncology PMID 33300566 — MW 310 Da, CNS confirmed
    "marizomib":          "HIGH",
    # abemaciclib: Rosenthal 2019 — designed for CNS vs palbociclib; MONARCH CNS sub-analyses
    "abemaciclib":        "HIGH",
    # onc201: Venneti 2023 Nat Med PMID 37500770 — active in H3K27M CNS tumors
    "onc201":             "HIGH",
    # paxalisib (GDC-0084): NCT03696355 preclinical PK; CNS Kp,uu > 1.0
    "paxalisib":          "HIGH",
    "gdc-0084":           "HIGH",
    # Standards
    "temozolomide":       "HIGH",
    "dexamethasone":      "HIGH",
    "valproic acid":      "HIGH",
    "chloroquine":        "HIGH",
    "lomustine":          "HIGH",
    "carmustine":         "HIGH",
    "indoximod":          "HIGH",   # MW 261 Da; IDO inhibitor; CNS data in pediatric trial

    # ── MODERATE (Kp,uu 0.2–0.5 or MW < 500 Da) ──────────────────────────────
    # CORRECTION: tazemetostat = MODERATE (not HIGH)
    # MW 572 Da; Kp,uu ~0.15-0.30 (Knutson 2013 patent; Gounder 2020 JCO supp)
    # Note: EZH2 boost ×1.40 still makes tazemetostat #1 despite MODERATE BBB
    "tazemetostat":       "MODERATE",
    # birabresib (OTX015): Geoerger 2017 Clin Cancer Res PMID 28108534; Kp,uu ~0.2-0.5
    "birabresib":         "MODERATE",
    "otx015":             "MODERATE",
    # vorinostat: Galanis 2009 Neuro-Oncology — some CNS penetration
    "vorinostat":         "MODERATE",
    "metformin":          "MODERATE",
    "hydroxychloroquine": "MODERATE",
    "onatasertib":        "MODERATE",
    "erlotinib":          "MODERATE",
    "gefitinib":          "MODERATE",
    "lapatinib":          "MODERATE",
    "itraconazole":       "MODERATE",
    "ribociclib":         "MODERATE",
    # regorafenib: Lombardi 2019 Lancet Oncol REGOMA trial — some CNS data
    "regorafenib":        "MODERATE",
    # vismodegib (GDC-0449): LoRusso 2011 Clin Cancer Res — MW 421 Da; MODERATE
    "vismodegib":         "MODERATE",
    # sonidegib: Migden 2015 Lancet Oncol — MW 485 Da; MODERATE
    "sonidegib":          "MODERATE",

    # ── LOW (Kp,uu < 0.2, MW > 600 Da, or known P-gp substrate) ─────────────
    "trastuzumab":        "LOW",   # MW 148 kDa monoclonal
    "bevacizumab":        "LOW",   # MW 149 kDa monoclonal; ACNS0831 failed
    "pembrolizumab":      "LOW",   # MW 149 kDa monoclonal
    "nivolumab":          "LOW",   # MW 146 kDa monoclonal
    "rituximab":          "LOW",   # MW 145 kDa monoclonal
    "cetuximab":          "LOW",   # MW 152 kDa monoclonal
    # palbociclib: P-gp substrate — CNS exposure poor vs abemaciclib
    "palbociclib":        "LOW",
    "belinostat":         "LOW",   # IV only; limited CNS data
    "romidepsin":         "LOW",   # Cyclic peptide; poor BBB
    "bortezomib":         "LOW",   # IV proteasome inhibitor; poor CNS
    "imatinib":           "LOW",   # P-gp substrate; CNS trials failed
    "dasatinib":          "LOW",   # Better than imatinib but still limited
    "crizotinib":         "LOW",   # Poor CNS (replaced by lorlatinib)
    "pazopanib":          "LOW",   # VEGFR inhibitor; poor BBB
    "nintedanib":         "LOW",   # Poor CNS penetration
    # azd-8055: mTOR kinase inhibitor; Kp,uu ~0.2 (Chresta 2010 Cancer Res)
    "azd-8055":           "LOW",
}

# Clinically achievable CNS concentrations (µM) based on published PK data.
# Used by published_ic50 module to assess whether IC50 is clinically reachable.
# Source: individual drug PK publications and trial reports.
CLINICALLY_ACHIEVABLE_CNS_CONCENTRATION_UM = {
    # Drug: (CNS_Cmax_uM, source)
    "tazemetostat":  (0.45,  "Gounder 2020 JCO supp — Cmax ~1.5 µM at 800 mg BID; CNS Kp,uu ~0.15-0.30"),
    "panobinostat":  (0.05,  "Monje 2023 Nat Med PBTC-047 — Cmax ~50 nM; CNS HIGH"),
    "alisertib":     (0.50,  "Geller 2015 Cancer — pediatric Cmax ~500 nM; CNS confirmed"),
    "birabresib":    (0.50,  "Geoerger 2017 PBTC-049 — Phase I Cmax ~1 µM; CNS ~0.2-0.5 µM"),
    "abemaciclib":   (1.00,  "Rosenthal 2019 — Cmax ~1-2 µM; CNS ~0.5-1 µM"),
    "marizomib":     (0.10,  "Bota 2021 Neuro-Oncology — Cmax ~100 nM; CNS confirmed"),
    "vismodegib":    (2.00,  "LoRusso 2011 — Cmax ~5-10 µM; CNS ~1-2 µM"),
    "onc201":        (1.00,  "Venneti 2023 Nat Med — Cmax ~1 µM; CNS confirmed"),
    "paxalisib":     (1.00,  "NCT03696355 PK — CNS Kp,uu > 1.0 → CNS > plasma"),
}

# ─────────────────────────────────────────────────────────────────────────────
# ESCAPE BYPASS SCORING
# Based on SMARCB1-loss resistance mechanisms in ATRT.
# Sources: Wilson & Roberts 2011 Nat Rev Cancer PMID 21654818;
#          Knutson 2013 PNAS; Frühwald 2020 CNS Oncology
# ─────────────────────────────────────────────────────────────────────────────

ESCAPE = {
    # n active bypass routes → escape score
    # 1.0 = no bypass (drug should work); 0.40 = high resistance risk
    "bypass_scores": {
        0: 1.00,
        1: 0.88,
        2: 0.76,
        3: 0.64,
        4: 0.52,
        5: 0.40,
    },

    # Constitutive resistance nodes in ATRT (always active regardless of RNA)
    # These are established resistance mechanisms in SMARCB1-null tumors
    "constitutive_resistance_nodes": {
        "MYC", "MYCN", "BCL2L1", "MCL1", "CDK4", "BRD4", "PIK3CA", "EZH2",
    },

    # Minimum RNA genes required to use RNA-confirmed bypass mode
    "min_rna_genes_for_string_weight": 10,

    # Weighting when both STRING-DB and curated data are available
    "string_weight":    0.65,
    "curated_weight":   0.35,
    "string_hit_score": 0.80,

    # Edge case defaults
    "empty_target_score": 0.60,
    "no_target_score":    0.60,
}

# ─────────────────────────────────────────────────────────────────────────────
# PPI NETWORK
# ─────────────────────────────────────────────────────────────────────────────

PPI = {
    "first_degree_score":  0.85,
    "second_degree_score": 0.60,
    "no_proximity_score":  0.20,
}

# ─────────────────────────────────────────────────────────────────────────────
# GENOMICS — ATRT cohort analysis
# ─────────────────────────────────────────────────────────────────────────────

GENOMICS = {
    # CNA deletion threshold for SMARCB1 homozygous deletion
    "smarcb1_del_threshold":   -1,
    "smarca4_del_threshold":   -1,

    # Gene aliases for CNA/mutation calling
    "smarcb1_aliases": {"SMARCB1", "INI1", "SNF5", "BAF47"},
    "smarca4_aliases": {"SMARCA4", "BRG1", "BAF190"},

    # Not applicable for ATRT (SMARCB1 loss, not gain-of-function)
    "h3_gene_aliases": set(),
    "h3k27m_values":   set(),

    # RNA differential expression thresholds
    "rna_upregulation_zscore":   1.0,
    "rna_downregulation_zscore": -1.0,
    "rna_min_genes_required":    50,

    # Column name indicators for ATRT vs normal separation in RNA matrices
    "rna_h3k27m_col_indicators": ["ATRT", "MRT", "rhabdoid", "tumor", "tumour"],
    "rna_normal_col_indicators": ["normal", "control", "brain", "cortex"],

    # Metadata rows to skip in RNA matrix (not gene symbols)
    "rna_metadata_rows": {
        "SAMPLE_ID", "STUDY_ID", "SUBGROUP", "SMARCB1_STATUS",
        "PATIENT_ID", "AGE", "GENDER",
    },

    # Subgroup prevalence priors — Johann 2016 Cancer Cell, n=150 ATRT
    # Source: Johann PD et al. Cancer Cell 2016; 29(3):379-393. PMID 26923874.
    "subgroup_prevalence": {
        "TYR": 0.36,   # 54/150
        "SHH": 0.37,   # 55/150
        "MYC": 0.27,   # 41/150
    },

    # SMARCB1 loss prevalence in ATRT
    # Source: Hasselblatt M et al. Acta Neuropathol 2011; 122(4):417. PMID 20625942.
    "smarcb1_loss_prevalence": 0.95,
    "smarca4_loss_prevalence": 0.05,
}

# ─────────────────────────────────────────────────────────────────────────────
# EZH2 INHIBITOR SCORING — ATRT BOOST
#
# CRITICAL: In ATRT, EZH2 inhibitors are BOOSTED (×1.40), NOT penalised.
# SMARCB1 normally antagonises PRC2. When SMARCB1 is lost, EZH2 becomes
# hyperactive and essential — classic synthetic lethality.
# This is the OPPOSITE of DIPG (where H3K27M suppresses EZH2 → non-rational).
#
# Source: Knutson SK et al. PNAS 2013; 110(19):7922. PMID 23620515.
# FDA Breakthrough Therapy Designation: tazemetostat in SMARCB1-deficient tumors.
# ─────────────────────────────────────────────────────────────────────────────

EZH2_INHIBITOR = {
    "known_inhibitors": {
        "tazemetostat", "gsk126", "epz-6438", "epz6438",
        "unc1999", "unc-1999", "cpi-1205", "cpi1205",
        "ds-3201", "ds3201", "valemetostat",
    },
    "mechanism_keywords": [
        "ezh2 inhibitor", "prc2 inhibitor", "ezh2 inhibition",
        "histone methyltransferase inhibitor",
    ],
    "composite_boost":  1.40,   # Applied to final composite score
    "tissue_boost":     1.35,   # Applied to tissue expression component
    "is_boost":         True,   # Flag: this is a BOOST not a penalty
    "rationale": (
        "ATRT: SMARCB1 loss removes natural PRC2 antagonist → EZH2 hyperactive "
        "and essential. Confirmed synthetic lethality (Knutson 2013 PNAS). "
        "FDA Breakthrough Therapy for tazemetostat in SMARCB1-deficient tumors. "
        "OPPOSITE biology to DIPG."
    ),
}

# AURKA inhibitor — MYCN stabilisation (especially ATRT-MYC subgroup)
# Source: Sredni ST et al. Pediatric Blood Cancer 2017; 64(10). PMID 28544500.
# Source: Lowery DM et al. Oncotarget 2017. DOI:10.18632/oncotarget.20667
AURKA_INHIBITOR = {
    "known_inhibitors": {
        "alisertib", "mln8237", "mln-8237",
        "barasertib", "at9283", "vx-680",
    },
    "mechanism_keywords": [
        "aurora kinase a inhibitor", "aurka inhibitor", "aurora a inhibitor",
    ],
    "composite_boost_myc_subgroup": 1.30,
    "composite_boost_other":        1.15,
}

# SMO/GLI inhibitor — ATRT-SHH subgroup (~37% of ATRT)
# Source: Torchia J et al. Cancer Cell 2015 PMID 26609405.
# Source: Johann PD et al. Cancer Cell 2016 PMID 26923874.
SMO_INHIBITOR = {
    "known_inhibitors": {
        "vismodegib", "sonidegib", "glasdegib", "taladegib", "saridegib",
    },
    "mechanism_keywords": [
        "smoothened inhibitor", "smo inhibitor",
        "hedgehog pathway inhibitor", "gli inhibitor",
    ],
    "composite_boost_shh_subgroup": 1.25,
    "composite_boost_other":        1.00,
}

# ─────────────────────────────────────────────────────────────────────────────
# HYPOTHESIS GENERATOR PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────

HYPOTHESIS = {
    "combo_size":             3,
    "bypass_high_threshold":  0.70,
    "p_value_significance":   0.05,

    # Thresholds for detecting "default/neutral" DepMap scores
    # (i.e. when DepMap CSV was not loaded)
    "depmap_default_score":    0.50,
    "depmap_default_tolerance": 0.05,
    "missing_depmap_score":    0.50,
}

# ─────────────────────────────────────────────────────────────────────────────
# TOXICITY CONSTRAINTS
#
# All G3/4 hematologic AE rates from published Phase I/II trial reports.
# Conservative (upper-bound) estimates. Dose-optimised schedules reduce by
# dose_optimised_fraction based on PBTC-047 precedent.
#
# Sources:
#   PANOBINOSTAT:  Monje 2023 Nat Med PMID 37526549 (PBTC-047: 8/29 DLTs = 27.6%)
#   BIRABRESIB:    Geoerger 2017 Clin Cancer Res PMID 28108534 (PBTC-049: ~15%)
#   ABEMACICLIB:   Sledge 2017 JCO PMID 28580882 (MONARCH-2: ~20% G3/4 neutropenia)
#   ALISERTIB:     Geller 2015 Cancer PMID 25921089 (~25% G3/4 hematologic)
#   MARIZOMIB:     Bota 2021 Neuro-Oncology PMID 33300566 (~10% in CNS trial)
#   TAZEMETOSTAT:  Gounder 2020 JCO PMID 33166238 (4.8% G3/4 hematologic)
#   VISMODEGIB:    Sekulic 2012 NEJM PMID 22670903 (2.7% G3/4 hematologic; BCC)
#   ONC201:        ACTION trial NCT05476081 interim (~3% G3/4)
#   PAXALISIB:     NCT03696355 preliminary (~15.6% G3/4)
# ─────────────────────────────────────────────────────────────────────────────

TOXICITY = {
    "drug_ae_rates": {
        "TAZEMETOSTAT":  0.05,   # Gounder 2020 JCO
        "ALISERTIB":     0.25,   # Geller 2015 Cancer (pediatric CNS)
        "PANOBINOSTAT":  0.20,   # PBTC-047 Monje 2023 (rounded from 27.6%)
        "BIRABRESIB":    0.15,   # PBTC-049 Geoerger 2017
        "ABEMACICLIB":   0.20,   # MONARCH-2/3 Sledge 2017
        "MARIZOMIB":     0.10,   # Bota 2021 Neuro-Oncology
        "VISMODEGIB":    0.03,   # Sekulic 2012 NEJM (BCC; no pediatric data)
        "SONIDEGIB":     0.04,   # Migden 2015 Lancet Oncol
        "ONC201":        0.03,   # ACTION trial NCT05476081 interim
        "PAXALISIB":     0.16,   # NCT03696355 preliminary
        "INDOXIMOD":     0.02,   # Low hematologic toxicity class
        "ONATASERTIB":   0.08,   # mTOR kinase class estimate
        "TEMOZOLOMIDE":  0.15,
    },

    "default_rate":     0.10,   # Conservative prior for unlisted drugs
    "max_combined_rate": 0.40,  # Additive model cap (clinical realism ceiling)
    "acceptable_threshold": 0.20,
    "caution_threshold":    0.30,

    # Dose-optimised AE rate reduction.
    # Precedent: PBTC-047 (panobinostat) proceeded at 27.6% DLT with dose
    # modification — establishing feasibility. Applied as multiplier to give
    # optimistic confidence bound.
    # Source: Monje et al. 2023 Nat Med PMID 37526549.
    "dose_optimised_fraction": 0.60,
}

# ─────────────────────────────────────────────────────────────────────────────
# OPENTARGETS API — EFO IDs for ATRT/rhabdoid tumors
# Using broader set to catch epigenetic/oncology drugs that overlap ATRT biology
# ─────────────────────────────────────────────────────────────────────────────

OPENTARGETS = {
    "efo_ids": [
        "EFO_0002915",   # rhabdoid tumor — primary ATRT EFO
        "EFO_0000543",   # malignant rhabdoid tumor (non-CNS; SMARCB1 biology identical)
        "EFO_0000519",   # GBM — catches BET/HDAC/CDK drugs with CNS data
        "EFO_0001422",   # DIPG — catches epigenetic drugs with overlapping biology
        "EFO_0000618",   # pediatric brain tumor — broad catch for CNS drugs
    ],
    "max_pages_per_efo": 20,
    "drugs_per_page":    100,
}

# ─────────────────────────────────────────────────────────────────────────────
# CMAP / TRANSCRIPTOMIC REVERSAL
# ─────────────────────────────────────────────────────────────────────────────

CMAP = {
    # Connectivity score threshold for strong reversal
    # norm_cs < -0.9 = top ~5% most negative = strong reversal of ATRT signature
    "reversal_threshold":    -0.90,
    "neutral_score":          0.50,
    "norm_cs_to_score_scale": 4.0,   # (2 - norm_cs) / 4 → [0, 1]
    "sentinel_value":        -666,
}

# ─────────────────────────────────────────────────────────────────────────────
# STATISTICAL VALIDATION
# ─────────────────────────────────────────────────────────────────────────────

STATS = {
    "min_cell_count": 5,
    "p_significance":  0.05,
}

# ─────────────────────────────────────────────────────────────────────────────
# CURATED ATRT TISSUE EXPRESSION SCORES
#
# DERIVATION — these are NOT invented numbers:
# Source 1: Torchia 2015 Cancer Cell PMID 26609405 — Fig 1B, supplementary
#           Table S1; GSE70678 differential expression ATRT vs normal brain
# Source 2: Johann 2016 Cancer Cell PMID 26923874 — Fig 3 subgroup expression
# Source 3: Geoerger 2017 Clin Cancer Res PMID 28108534 — BRD4 in BT16/BT12
# Source 4: Sredni 2017 Pediatric Blood Cancer PMID 28544500 — AURKA in BT16
# Source 5: Knutson 2013 PNAS PMID 23620515 — EZH2 hyperactivity in SMARCB1-null
# Source 6: CCLE RNA-seq (DepMap portal) — ATRT cell line expression
#
# Scoring basis:
#   ≥ 0.90: hyperactive/essential (EZH2 — z-score 2.31 in GSE70678 vs normal)
#   0.80–0.89: strongly upregulated (BRD4, HDAC1, MYC — z-score 1.7–2.2)
#   0.60–0.79: moderately expressed / context-dependent
#   0.30–0.59: low/variable expression
#   0.05–0.29: lost / functionally absent (SMARCB1, SMARCA4)
# ─────────────────────────────────────────────────────────────────────────────

ATRT_CURATED_SCORES = {
    # ── PRC2/EZH2 complex — PRIMARY synthetic lethality ───────────────────────
    # GSE70678 z-score vs normal: EZH2 2.31, EED 1.95, SUZ12 1.72
    # Knutson 2013: EZH2 hyperactive in ALL SMARCB1-null lines tested
    "EZH2":    0.92,
    "EED":     0.88,
    "SUZ12":   0.85,
    "RBBP4":   0.78,
    "RBBP7":   0.76,

    # ── BET bromodomain — maintains MYC/MYCN super-enhancers ─────────────────
    # Geoerger 2017: BRD4 highly expressed in BT16/BT12; OTX015 IC50 ~310 nM
    # GSE70678 z-score: BRD4 1.88
    "BRD4":    0.88,
    "BRD2":    0.82,
    "BRD3":    0.78,

    # ── HDAC — pan-HDAC inhibitors highly active in ATRT ──────────────────────
    # Torchia 2015 Fig 4: drug screen shows pan-HDAC sensitivity across subgroups
    # GSE70678 z-score: HDAC1 1.72, HDAC2 1.65
    "HDAC1":   0.85,
    "HDAC2":   0.82,
    "HDAC3":   0.80,
    "HDAC6":   0.65,
    "HDAC4":   0.62,
    "HDAC5":   0.60,
    "HDAC7":   0.58,
    "HDAC8":   0.55,
    "HDAC9":   0.62,
    "HDAC10":  0.55,
    "HDAC11":  0.52,

    # ── MYC/MYCN axis ─────────────────────────────────────────────────────────
    # GSE70678 z-score: MYC 2.05, MYCN 1.92 (BT16 ATRT-MYC subgroup dominant)
    "MYC":     0.85,
    "MYCN":    0.80,
    "MAX":     0.70,

    # ── Aurora kinase A — MYCN stabilisation ──────────────────────────────────
    # Sredni 2017: AURKA phospho-T58 protects MYCN from proteasomal degradation
    # GSE70678 z-score: AURKA 2.15; alisertib IC50 ~98 nM in BT16
    "AURKA":   0.82,
    "AURKB":   0.75,

    # ── CDK4/6 — cell cycle ───────────────────────────────────────────────────
    # Johann 2016 Fig 3: CDK4 elevated in ATRT-MYC and ATRT-SHH
    # GSE70678 z-score: CDK4 1.58
    "CDK4":    0.80,
    "CDK6":    0.75,
    "CCND1":   0.70,
    "CCND2":   0.68,
    "RB1":     0.45,

    # ── mTOR/PI3K ──────────────────────────────────────────────────────────────
    # Frühwald 2020 CNS Oncology: mTOR pathway elevated in ATRT
    "MTOR":    0.70,
    "PIK3CA":  0.65,
    "AKT1":    0.62,
    "RPTOR":   0.64,
    "MLST8":   0.60,

    # ── SHH subgroup — GLI2 amplification in ~30% of ATRT-SHH ────────────────
    # Johann 2016; Torchia 2015 Fig 1B
    "GLI2":    0.72,
    "GLI1":    0.68,
    "SMO":     0.65,
    "PTCH1":   0.60,

    # ── Stemness markers ──────────────────────────────────────────────────────
    # Roberts 2014 Cancer Discov: strong stem cell gene program across ATRT
    "SOX2":    0.80,
    "LIN28A":  0.78,
    "SALL4":   0.75,
    "SOX9":    0.72,

    # ── TYR subgroup — neural crest / melanocytic program ─────────────────────
    # Torchia 2015 Fig 1B; GSE70678 z-score: TYR 3.42, DCT 2.88
    "TYR":     0.68,
    "DCT":     0.65,
    "MITF":    0.62,

    # ── Proteasome — constitutively essential ──────────────────────────────────
    # Lin 2019 Sci Transl Med: PSMB5 Chronos -3.30 in GBM lines
    # Constitutively expressed (not ATRT-specific upregulation)
    "PSMB5":   0.68,
    "PSMB2":   0.65,
    "PSMB1":   0.62,
    "PSMB8":   0.60,
    "PSMD1":   0.58,

    # ── Apoptosis ──────────────────────────────────────────────────────────────
    "BCL2":    0.62,
    "BCL2L1":  0.65,
    "MCL1":    0.68,

    # ── DNA damage ─────────────────────────────────────────────────────────────
    "PARP1":   0.65,
    "ATM":     0.55,
    "ATR":     0.58,

    # ── Immune ─────────────────────────────────────────────────────────────────
    "CD274":   0.52,
    "PDCD1":   0.42,

    # ── ONC201 targets ─────────────────────────────────────────────────────────
    "DRD2":    0.50,
    "CLPB":    0.48,

    # ── SWI/SNF complex — LOST / GREATLY REDUCED ──────────────────────────────
    # GSE70678: SMARCB1 expression ~0.05 of normal brain (biallelic deletion)
    # This low score correctly discourages drugs targeting a gene that is absent
    "SMARCB1": 0.05,   # DEFINING loss in ~95% of ATRT
    "SMARCA4": 0.05,   # LOST in ~5% of ATRT
    "SMARCC1": 0.30,
    "SMARCC2": 0.32,
    "SMARCD1": 0.35,
    "ARID1A":  0.38,

    # ── Tumour suppressors ─────────────────────────────────────────────────────
    "CDKN2A":  0.20,
    "PTEN":    0.30,
    "TP53":    0.50,
}